### ISSUE TITLE
Inserted null values

### ISSUE THREAD

**Issue by marcverhagen** [lapps/org.lappsgrid.serialization#56]
Handing a SOAP request to a service can cause trouble if the request has an incomplete LIF object. For example, sending the following causes trouble.

```json
{
    "discriminator": "http://vocab.lappsgrid.org/ns/media/jsonld#lif", 
    "payload": {
        "text": {
            "@value": "The door."
        }
    }
}
```

But this is fine:

```json
{
    "discriminator": "http://vocab.lappsgrid.org/ns/media/jsonld#lif", 
    "payload": {
        "@context": "http://vocab.lappsgrid.org/context-1.0.0.jsonld",
        "metadata": {},
        "text": {
            "@value": "The door is open."
        },
        "views": []
    }
}
```

The error we get for the former is

```
Traceback (most recent call last):
  File "lapps.py", line 66, in <module>
    result = json.loads(client.service.execute(service_input))
  File "/usr/local/lib/python3.6/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.lappsgrid.serialization.Utils#deepCopy.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[interface java.util.List]
	[interface java.util.Map]
	[interface java.util.Set]
```

This was done using zeep in a Python script using `http://eldrad.cs-i.brandeis.edu:8080/service_manager/wsdl/brandeis_eldrad_grid_1:stanfordnlp.tokenizer_2.0.4`. The error can be replicated with SoapUI.

**Comment by ksuderman** [comment]
I suspect [this line](https://github.com/lapps/org.lappsgrid.serialization/blob/683086d004fd80cb1d1b2fb34576ca649c53d87d/src/main/groovy/org/lappsgrid/serialization/lif/Container.groovy#L287) is the problem.  It should be checking if `map.metadata` is null before calling `Utils.deepCopy`.
